version: "3"
services:
  web:
    build: .
    volumes:
      - ..:/workspaces/remote-container-demo
    command: /bin/sh -c "while sleep 1000; do :; done"
  database:
    image: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: s$cret
      POSTGRES_DB: testdb